### ISSUE TITLE
In jsx props, I expect this convert feature

### ISSUE THREAD

**Issue by utadachiren** [meganrogge/template-string-converter#15]
Sorry, I couldn't make it a concise title, I couldn't put it into words. But it's easy to express in code.

from

```
const Hoge = ({ hoge }) => <input value="${hoge}" />
```

to

```
const Hoge = ({ hoge }) => <input value={`${hoge}`} />
```

**Comment by meganrogge** [comment]
Hi, can you please describe the use case of this more broadly? Is this a specific feature of jsx?

**Comment by karlhorky** [comment]
So, I believe this request is about supporting the single and double quotes in JSX props.

For example, both of the components in this code here below are using hardcoded string values as the value for the `name` prop:

```jsx
const Component1 = () => <Greet name="Karl" />
const Component2 = () => <Greet name='Karl' />
```

If they were to be updated to use a `${` inside of the values, such as this step here:

```jsx
const Component1 = () => <Greet name="${user.name}" />
const Component2 = () => <Greet name='${user.name}' />
```

...then the Template String Converter VS Code Plugin could convert them to this:

```jsx
const Component1 = () => <Greet name=`${user.name}` />
const Component2 = () => <Greet name=`${user.name}` />
```

Does this make sense?

**Comment by meganrogge** [comment]
Thanks for the additional info. This works as is shown below.

![example](https://user-images.githubusercontent.com/29464607/95880321-3abb2f00-0d2c-11eb-8ff6-45732e1aed1c.gif)

**Comment by karlhorky** [comment]
Ah, sorry about this - I made a mistake in my post above! (now updated)

In JSX, if you want to use a template string in a prop, you need to wrap it in curly brackets, like this:

```jsx
const Component1 = () => <Greet name={`${user.name}`} />
const Component2 = () => <Greet name={`${user.name}`} />
```

**Comment by karlhorky** [comment]
Almost - the curly brackets (to create an [embedded expression](https://reactjs.org/docs/introducing-jsx.html#embedding-expressions-in-jsx)) should be added **only if they don't exist already**.

So a pseudo-code algorithm could look like this:

1. Are we inside a tag? (either `<...>` or `<.../>`)
2. Are we in the value of a prop? (eg. we're in between `propName="` and `"` in this code: `<tagname propName="..."></tagname>`)
3. Are we inside an embedded expression (the curly brackets) in JSX?

If 1 and 2 are true but 3 is not, add curly brackets around the backticks. In all other cases, keep the existing behavior.

If this algorithm could run using abstract syntax tree information instead of string matching (so that it only ran on JavaScript files inside of JSX parts), then I guess it could be pretty robust (and also default).

**Comment by utadachiren** [comment]
Thank you karlhorky. you have filled in all the missing pieces.

**Comment by meganrogge** [comment]
@karlhorky @utadachiren thank you for the feedback and info. I've been pretty busy this week, but hope to get to this sometime next week.

**Comment by meganrogge** [comment]
alright @karlhorky @utadachiren @capaj try it out and let me know what you think.

**Comment by karlhorky** [comment]
wowow so fast, thanks @meganrogge! I'll give it a go!

**Comment by karlhorky** [comment]
Hm... just upgraded to version 0.2.0 and... it doesn't seem to be working (at least with `javascript` and `javascriptreact` syntaxes).

Am I doing something wrong?

### `javascript` syntax

![Kapture 2020-10-19 at 11 09 36](https://user-images.githubusercontent.com/1935696/96424911-ad7c4c80-11fb-11eb-9d3b-1a139d5a0c1c.gif)

### `javascriptreact` syntax

![Kapture 2020-10-19 at 11 09 58](https://user-images.githubusercontent.com/1935696/96424934-b79e4b00-11fb-11eb-83c1-e927c30980ef.gif)

**Comment by meganrogge** [comment]
I made it such that this only works when you’re assigning a variable. So try `let result=` that expression please. The reason for doing this is I want to be sure it’s not firing for non-props. Let me know if you think there’s a better way to restrict this.

**Comment by karlhorky** [comment]
> I made it such that this only works when you’re assigning a variable. So try `let result=` that expression please.

hmm... not sure exactly what you mean. Where would I put `let result=`? This is not a JavaScript expression.

> This should work for your earlier examples above

> this will only works in JavaScript react/ typescript react files

Ok, I tried writing the following in a `javascriptreact` file:

```jsx
const Component1 = () => <Greet name="Karl" />
```

...and tried adding `${` inside the quotes after `"`, but this also didn't work (no effect, no changing of quotes).

**Comment by meganrogge** [comment]
Sorry about this - I’ll investigate. It was working for me last night.

**Comment by meganrogge** [comment]
![recording (7)](https://user-images.githubusercontent.com/29464607/96477987-fdebae00-11eb-11eb-9179-98e056b201f3.gif)

@karlhorky it should now work in v 0.2.1

**Comment by utadachiren** [comment]
This is the behavior I was hoping for.
thanks @meganrogge @karlhorky

**Comment by karlhorky** [comment]
Thanks @meganrogge ! It works in some simple cases! 🙌

However, there are still a few bugs. For example:

1. an element that has a `-` in the prop value
2. multiple props

See in the gif:

![Kapture 2020-10-20 at 11 54 34](https://user-images.githubusercontent.com/1935696/96571274-a15fc000-12cb-11eb-8265-879cc6d182fd.gif)

...or using something else, like using JS Object Spread to put all of the props passed in as arguments:

![Screen Shot 2020-10-20 at 11 55 32](https://user-images.githubusercontent.com/1935696/96571118-77a69900-12cb-11eb-9acb-9845f0192fd3.png)

**Comment by meganrogge** [comment]
@karlhorky should now work for all of the above

**Comment by karlhorky** [comment]
Great, looking really good! Thanks @meganrogge ! 🙌

One last broken case that I can think of is newlines:

```jsx
function Div(props) {
  return (
    <div
      {...props}
      prop-on-new-line="abc"
      // comment
      another-on-new-line="def"
    />
  );
}
```

![Kapture 2020-10-22 at 10 55 51](https://user-images.githubusercontent.com/1935696/96848959-5671b400-1455-11eb-9fa3-cf61b3f89a7b.gif)

**Comment by meganrogge** [comment]
@karlhorky that's expected. As of now, this extension doesn’t deal with multiline.

**Comment by karlhorky** [comment]
Ok, I will open a separate issue about this, in case anyone ends up searching for this.

Thanks for your hard work on this!

**Comment by meganrogge** [comment]
@karlhorky can you pls specify that this is a known issue?

**Comment by karlhorky** [comment]
Will do, sure!
