### ISSUE TITLE
Suggestion: If ${} is removed, turn back into a regular string. 

### ISSUE THREAD

**Issue by RobiFerentz** [meganrogge/template-string-converter#16]
It's a common lint rule that if there are no variables in string, it should not be a template string, so this could really help avoid lint errors. (yes, I'm aware that formatting can fix this, but on the fly is nicer)

**Comment by EliasGcf** [comment]
This would be very good

**Comment by meganrogge** [comment]
I like this idea, but think the implementation would be complicated / out of scope for this extension. I'll leave this open to see how much enthusiasm this garners though.

**Comment by karlhorky** [comment]
I guess this feature was originally implemented in #19, but it doesn't seem to be working in `0.4.7` - was it reverted again?

If so, should this issue be re-opened?

**Comment by meganrogge** [comment]
Do you have the setting enabled?

Nothing has changed

**Comment by karlhorky** [comment]
Ah, it's a setting! Sorry, I'll try it out.

**Comment by karlhorky** [comment]
Ah, it's a setting! Sorry, just trying it out...

Ok, seems to be working! 🙌  The only weird UX thing is that my cursor jumped to the end of the string when I removed the `}` in the `${}`.

**Comment by karlhorky** [comment]
Oh, one more: If I create a new tagged template literal like this:

```
css``
```

...as soon as I type the second backtick, it changes them to double quotes 😲

Should I open a new issue for this?

**Comment by meganrogge** [comment]
Sure cc @xNocken, who added this setting and feature.

**Comment by karlhorky** [comment]
Done, also found some more buggy cases: #43
