### ISSUE TITLE
Wrong conversion for nested strings

### ISSUE THREAD

**Issue by loilo** [meganrogge/template-string-converter#18]
Issue Type: Bug

---

Here's a GIF of me reproducing the issue:

![The issue author reproducing the issue in VS Code](https://user-images.githubusercontent.com/1922624/96470489-a0c51c00-122e-11eb-8132-4d3162f920d9.gif)

---

For the code:

```js
'I said: "Hello world!"'
```

After the "Hello", type `${`

**Expected**
This should result in:

```js
`I said: "Hello ${}world!"`
```

**Actual**
The part between the double quotes is converted:

```js
'I said: `Hello ${}world!`'
```

Extension version: 0.2.0
VS Code version: 1.50.0
OS version: macOS 10.15.7

**Comment by loilo** [comment]
I just realized that the extension generally does not seem to work in single-quote strings that contain a double quote.

If you take the same example string from above:

```
'I said: "Hello world!"'
```

And type `${` after "said", nothing will happen.

**Comment by BobbieGoede** [comment]
This works as expected by setting `template-string-converter.quoteType` to `single` in settings on my end.

**Comment by loilo** [comment]
So, is this a "works as intended", @meganrogge?

**Comment by meganrogge** [comment]
@lolio yes. are you suggesting it should work another way?

**Comment by loilo** [comment]
From an intuitive perspective I'd say yes. The extension should not change the *contents* of my string (which it currently does when replacing double quotes with backticks *inside* the single-quoted string).

The `"Hello world!"` from my original example is just as much an arbitrary substring as `said: "Hello` or `!"`; none of those have any semantic meaning. Therefore I would not expect it to be converted.

**Comment by meganrogge** [comment]
@loilo I've now added a setting that handles nested quotes as you describe.

**Comment by loilo** [comment]
Works like a charm — thank you!
