### ISSUE TITLE
Respect editor.autoClosingBrackets = never

### ISSUE THREAD

**Issue by Tyriar** [meganrogge/template-string-converter#21]
I have `"editor.autoClosingBrackets": "never"` set and when I do my normal thing this ends up happening:

![recording (2)](https://user-images.githubusercontent.com/2193314/97311795-fa76a900-1821-11eb-97d6-e04ddaffcf0f.gif)

Can the extension check that setting and if it's `never`, still convert to a template string but not inject the trailing `}` and not move the cursor?

**Comment by meganrogge** [comment]
Yes that shouldn’t be happening. I will look into it today. Did this just happen for the first time recently? I just merged a PR

**Comment by Tyriar** [comment]
That's actually showing the problem I'm having; when `"editor.autoClosingBrackets": "never"` is set, I do not want the extension to add the `}` since users of that setting prefer to type the closing bracket themselves.

**Comment by meganrogge** [comment]
@Tyriar got it. I will add a conditional that checks that today.

**Comment by meganrogge** [comment]
fixed in v 0.2.5 that should be live in a few minutes! @Tyriar
