### ISSUE TITLE
Typing ${} quickly will not convert to template string

### ISSUE THREAD

**Issue by Tyriar** [meganrogge/template-string-converter#22]
Related: https://github.com/meganrogge/template-string-converter/issues/21

Typing `${}` quickly will move cursor to the middle of them but not convert to a template string.

![recording (3)](https://user-images.githubusercontent.com/2193314/97311990-3a3d9080-1822-11eb-82b9-361b841b85a0.gif)

**Comment by angelhdzdev** [comment]
Ooooh so that's what's happening to me for so many years!? I assumed it was a bug with the extension where sometimes it worked and sometimes it didn't, but now I think my problem is when I type `${` too fast!!! 🤯

Yup, confirmed it.
