### ISSUE TITLE
edge case

### ISSUE THREAD

**Issue by joshxyzhimself** [meganrogge/template-string-converter#23]
on this sample string,

```js
const asd = `
  SELECT *
  FROM ""
`;
```

typing "${}" within the double quotes turns it to

```js
const asd = `
  SELECT *
  FROM `${}`
`;
```

**Comment by meganrogge** [comment]
Yes that looks like a valid bug. I will fix it soon. Good catch!

**Comment by meganrogge** [comment]
fixed @joshxyzhimself

**Comment by joshxyzhimself** [comment]
Woah that was fast, thank you very much @meganrogge! love this extension very helpful 💯 💯
