### ISSUE TITLE
Possible to use with multiple cursor?

### ISSUE THREAD

**Issue by ktutnik** [meganrogge/template-string-converter#24]
Thanks for creating this great tool. 

I notice that the multiple cursor is till not supported, any plan to add it in near future?

**Comment by meganrogge** [comment]
@ktutnik cool idea. i'll work on it

**Comment by meganrogge** [comment]
![recording (34)](https://user-images.githubusercontent.com/29464607/98888806-83f6bf80-244d-11eb-9dcd-ebdb4facf78b.gif)
need to do some more validation tomorrow to make sure it won't break anything, but it's looking pretty good. should be released soon. @ktutnik

**Comment by ktutnik** [comment]
That's fast!

Thank you @meganrogge for making this feature available quickly

**Comment by meganrogge** [comment]
I’ll push the updated version tomorrow. Thanks for the idea!

**Comment by meganrogge** [comment]
done, should be live in a few minutes
