### ISSUE TITLE
Does not handle nested quotes

### ISSUE THREAD

**Issue by bduffany** [meganrogge/template-string-converter#25]
Input:

```
'Foo "bar${}" baz'
```

Actual result:

```
'Foo `bar${}` baz'
```

Expected result:

```
`Foo "bar${}" baz`
```

**Comment by meganrogge** [comment]
Thanks for the issue. I've made this setting `template-string-converter.convertOutermostQuotes`, which is false by default. going to do a bit more testing then will push the changes.
![recording (35)](https://user-images.githubusercontent.com/29464607/98974791-29e80f80-24ca-11eb-8ade-5d9bf56c73f8.gif)

**Comment by bduffany** [comment]
Just curious, why false by default? To me it seems kinda odd to have to enable a flag in order to fix a bug.

**Comment by meganrogge** [comment]
I don't want to surprise people with new behavior. I can see the argument for setting it to `true` by default though.
