### ISSUE TITLE
Converting strings that contain backticks?

### ISSUE THREAD

**Issue by JacksonKearl** [meganrogge/template-string-converter#26]
This is a bit specific so feel free to `*out-of-scope`, but it'd be nice if this could turn:

```
content = '```${'
```
into 
```
content = `\`\`\`${}`
```

**Comment by meganrogge** [comment]
not sure I understand the use case.....

**Comment by JacksonKearl** [comment]
It's a narrow use case, but I needed to build markdown strings using templates.

**Comment by meganrogge** [comment]
it does seem out of scope to me, but I could always add a setting that looks for this specific case. do you think others would find it useful?

**Comment by JacksonKearl** [comment]
I don't think there's much value to adding this as a specific case, but in general I'd expect it to still work if the string contains backtics and simply escape them.

**Comment by meganrogge** [comment]
I think most people don't want this to work if they're within backticks, such as #23 .

**Comment by JacksonKearl** [comment]
That's a different thing, what I'm taking about is
```
const a = 'this has some internal `backticks` and I'd like to insert a substitution ${'
```
to
```
const a = `this has some internal \`backticks\` and I'd like to insert a substitution ${}`
```

**Comment by meganrogge** [comment]
I think this is out of scope for now because the extension primarily focuses on the presence of quotes around the ${ as a precursor to any replacement. Thanks for the idea though.
