### ISSUE TITLE
VSCode/Vim clash: Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by joshmu** [meganrogge/template-string-converter#29]
Seems to be a clash with Vscode/Vim on the latest update of this extension.

[https://github.com/VSCodeVim/Vim/issues/5736](https://github.com/VSCodeVim/Vim/issues/5736)

**Comment by meganrogge** [comment]
@joshmu resolved

**Comment by joshmu** [comment]
Nice one! =)
