### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by brunolemos** [meganrogge/template-string-converter#34]
- Issue Type: `Performance`
- Extension Name: `template-string-converter`
- Extension Version: `0.3.6`
- OS Version: `Darwin x64 20.1.0`
- VSCode version: `1.52.0`

`meganrogge.template-string-converter-unresponsive.cpuprofile.txt`: https://pastebin.com/T12kmX1L

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by meganrogge** [comment]
Hi @brunolemos this should be resolved in version 0.3.7. if it is not, please let me know. thanks
