### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by amiroff** [meganrogge/template-string-converter#35]
This extension is so useful when usingReact that I miss it in personal Svelte projects. Is it possible to add support for Svelte components?

Cheers.

**Comment by meganrogge** [comment]
So glad it's useful for you. If you could give me some examples of what would be useful in svelte, I can work on it.

**Comment by amiroff** [comment]
Thanks for such quick feedback. Svelte uses a single file very much like HTML which has a traditional style and script scopes. Here is a live example: https://svelte.dev/examples#hello-world

There's a VSCode extension to enable support for .svelte files, it uses language server.  https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

**Comment by meganrogge** [comment]
Cool thanks. I'll look into it.

**Comment by madacol** [comment]
I simply added `"svelte"` to the supported languages, and it seems to work just fine
![image](https://user-images.githubusercontent.com/6379896/102953345-0fc52800-449f-11eb-9d92-f5a48a331274.png)

**Comment by meganrogge** [comment]
> I simply added `"svelte"` to the supported languages, and it seems to work just fine
> 
> ![image](https://user-images.githubusercontent.com/6379896/102953345-0fc52800-449f-11eb-9d92-f5a48a331274.png)
> 
> 

@amiroff

**Comment by amiroff** [comment]
@meganrogge @madacol yay! Tanks, cannot believe I somehow missed this, though I was sure to try this first before reporting. Now, rechecked, all is dandy!
