### ISSUE TITLE
Issue with quotes inside of strings

### ISSUE THREAD

**Issue by knecht-d** [meganrogge/template-string-converter#36]
First of all I really like the extension.
I is really handy when you want to add an expression to an existing string.

Unfortunately I came across the following issue:

Say you have a string like this
```js
const test = '"This is" "a test"';
``` 
and you add ${} between the inner quotes like this
```js
const test = '"This is" ${} "a test"';
``` 
I would expect, that the outer single quotes get converted to back-ticks, but unfortunately the inner ones get converted.

```js
// Expected
const test = `"This is" ${} "a test"`;
// Actual
const test = '"This is` ${} `a test"';
``` 

The same happens if you add `${}` in a template string which contains quotes.

**Comment by meganrogge** [comment]
Have you tried changing the setting convert outermost quotes to true?

**Comment by meganrogge** [comment]
works as you expect for me with that setting

![recording (76)](https://user-images.githubusercontent.com/29464607/102102248-6e740d00-3de0-11eb-9d1f-e5ba05c60eca.gif)
