### ISSUE TITLE
Extension doesn't recognize existing template literals

### ISSUE THREAD

**Issue by oliversalzburg** [meganrogge/template-string-converter#37]
Given the following piece of code:

```typescript
console.log( `User submitted: ''.` );
```

Place the caret in between the single quotes and type `${`. The code is converted to:

```typescript
console.log( `User submitted: `${`.` );
```

Which is not valid syntax.

**Comment by meganrogge** [comment]
That looks like a regression from my recent changes. I'll fix it today.

**Comment by meganrogge** [comment]
fixed! thanks for bringing this to my attention!

**Comment by oliversalzburg** [comment]
That was quick. Thanks a lot 😀

**Comment by meganrogge** [comment]
it's live now. you should just have to update and reload the window.

**Comment by oliversalzburg** [comment]
I'm sorry, but it seems like there has been another regression or the fix was only partially successful.

The previously reported case is fixed. However, the same behavior can still be observed for a second occurence of the pattern. For example:

```typescript
console.log( `User submitted: '${foo}' and also ''.` );
```

Putting the `${` in between the second `''` will convert them to backticks again.

**Comment by meganrogge** [comment]
Thanks I'll look into it

**Comment by meganrogge** [comment]
I had a request to convert to a template string when '${' is added within an existing template string. So this is actually working as I'd expect. Do you want me to add a setting so that you can turn this template string within a template string conversion off?

**Comment by oliversalzburg** [comment]
If there'd be an option like that, I'd appreciate it, but occassionally using _undo_ is still more convenient than having to convert to template strings manually 😊

**Comment by meganrogge** [comment]
added a setting you can toggle now @oliversalzburg

**Comment by oliversalzburg** [comment]
I'll give it a try 😀
