### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by spoenemann** [meganrogge/template-string-converter#40]
This project doesn't have any license. Please add one, preferably an [open source license](https://opensource.org/licenses) such as MIT.

A license is mandatory for publishing your extension to [Open VSX](https://open-vsx.org/). Its publishing tool [ovsx](https://www.npmjs.com/package/ovsx) offers to automatically add the MIT license when you try to publish without license. See the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) for more details.

**Comment by meganrogge** [comment]
Hey thanks for pointing this out. I'm traveling today, but will add one tomorrow.

**Comment by spoenemann** [comment]
Great! Could you also add `"license": "MIT"` to package.jon? That facilitates automatic processing.

**Comment by meganrogge** [comment]
done!
