### ISSUE TITLE
Unexpected replacement of double-quotes with back-ticks

### ISSUE THREAD

**Issue by chrmarti** [meganrogge/template-string-converter#41]
Issue Type: <b>Bug</b>

Place caret after $ and type opening curly brace:
```ts
`${`"$"`}`
```
Result:
```ts
`${``${}``}`
```

Extension version: 0.4.7
VS Code version: Code - Insiders 1.53.0-insider (eaa959d34b863dec932077d94daece22504a396b, 2021-01-18T05:11:47.400Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.53GB free)|
|Process Argv|-psn_0_6153694 --crash-reporter-id 7aad610c-0e6b-48aa-ba87-b704b1b543cf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
vstes516:30244333
pythonvspyt600:30241727
core-portspanelcf:30233468

```

</details>

**Comment by meganrogge** [comment]
This was a feature request - the conversion to a template string within a template string. You can turn it off with the setting template-string-converter.convertWithinTemplateString
