### ISSUE TITLE
Command to toggle any string to template string without having to write ${

### ISSUE THREAD

**Issue by bennysce** [meganrogge/template-string-converter#42]
I'm working on a project making lots of code translatable replacing tons of strings from

"Text" or <p>Text</p>

to

t\`Text\`

(due to the react i18n ttag library)

Would it be out of scope of this extension to add a hotkey command to at least be able to switch

"Text"

to

\`Text\`

just by having the cursor between the quotes and pressing CTRL+ALT+T or something (configurable, haven't checked what is available)?

**Comment by JohnGurin** [comment]
Look at this extension https://github.com/Pustelto/Bracketeer

**Comment by meganrogge** [comment]
hey thanks so much for this issue. I think that's out of scope for this extension bc there are others out there that do what you want
