### ISSUE TITLE
[Feature] Make this extension available for VSCode web

### ISSUE THREAD

**Issue by shivapoudel** [meganrogge/template-string-converter#50]
I'm often using VSCode web on GitHub and would love to have the same feature available. Currently, this extension can't be installed?

**Comment by meganrogge** [comment]
what error are you seeing? it's working for me on codespaces

**Comment by meganrogge** [comment]
![recording (60)](https://user-images.githubusercontent.com/29464607/130172243-dc66d548-e8e3-4279-b69d-52e83960c8b6.gif)

**Comment by shivapoudel** [comment]
@meganrogge Not working for repos open with `.` press still.
![image](https://user-images.githubusercontent.com/3774827/130184733-f6b8bc51-3612-4554-84c1-fbee55fb4271.png)
