### ISSUE TITLE
Template string converter in Web please

### ISSUE THREAD

**Issue by isidorn** [meganrogge/template-string-converter#57]
Hi Megan,

We recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser.  You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web). 

We'd like to ensure Template String Converter can run in the web, and we have a guide for enabling extensions for the web [here](https://code.visualstudio.com/api/extension-guides/web-extensions). As a couple of highlights:

- In VS Code for the Web, both the UI and extension host run inside the browser.
- A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
- Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
- There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

I checked your extension and I think it should be easy to convert it to work on the web.
@meganrogge you should just add to `package.json` a `browser` property that would have the same value as the `main` property.
Let me know if I can help

Isidor

**Comment by meganrogge** [comment]
![recording - 2021-11-23T110609 996](https://user-images.githubusercontent.com/29464607/143087973-db047a63-4a6b-4c19-a192-74c483dc15a1.gif)
