### ISSUE TITLE
Support disable this extension in glob files

### ISSUE THREAD

**Issue by tjx666** [meganrogge/template-string-converter#58]
I have a project which contains ES3 code and TS code. In ES3 code file, I don't want to enable this extension.

**Comment by meganrogge** [comment]
can you please provide me with an example?

**Comment by tjx666** [comment]
![image](https://user-images.githubusercontent.com/41773861/147716393-33cddaa4-aff4-4ab5-862f-0048d635fa35.png)

Because this extension, I can't using my custom logger like:

```
logger.debug('My name is ${name}', {
    placeholder: {
        name: 'bob'
    }
})
```
