### ISSUE TITLE
How to enable for .vue files?

### ISSUE THREAD

**Issue by snips-dev** [meganrogge/template-string-converter#69]
Cant make it work on .vue files

**Comment by meganrogge** [comment]
add to `template-string-converter.validLanguages`

**Comment by maruk0chan** [comment]
Hello, adding either "vue" or ".vue" doesn't work for me.
I'm using vue2 and may I know how to make it work?

```
  "template-string-converter.validLanguages": [
    "vue",
    ".vue",
    "svelte",
    "typescript",
    "javascript",
    "typescriptreact",
    "javascriptreact"
  ]
```

**Comment by gleenk** [comment]
Still not working for vue.
![Immagine 2023-04-23 100344](https://user-images.githubusercontent.com/848835/233827605-8ef668c0-badf-4b6f-b3ab-0f600ba77f2a.png)
