### ISSUE TITLE
I expect this extension should only work in typescript or javascript only

### ISSUE THREAD

**Issue by alyahmedaly** [meganrogge/template-string-converter#7]
I expect this extension should only work in typescript or JavaScript only but it's also working on other files type like scss
I know ${} is not valid scss but maybe check can make it better or only activate the extension when user open js or ts file.

Thanks for your awesome extension.

**Comment by meganrogge** [comment]
solved in version 0.1.1

**Comment by meganrogge** [comment]
solved in version 0.1.1
