### ISSUE TITLE
Extension Template String Converter not working

### ISSUE THREAD

**Issue by vicasas** [meganrogge/template-string-converter#77]
The extension unexpectedly stopped working in my vscode editor, when adding `${` to a string it does not make the change.

Visual Studio Code: v1.70.2
MacOS Monterey v12.5.1 (Chip M1)

**Comment by meganrogge** [comment]
could you pls provide a gif?

**Comment by vicasas** [comment]
I have the extension installed and have to reinstall and the problem persists.

![Sep-07-2022 20-03-11](https://user-images.githubusercontent.com/57921784/189005565-a9188779-1b59-41b7-b0f6-6f6295cba1c1.gif)

**Comment by meganrogge** [comment]
it expects a properly formed line of code IE a semicolon following that expression

**Comment by meganrogge** [comment]
it's hard to repro without your exact code - it's working for me

**Comment by meganrogge** [comment]
also what are your settings?

**Comment by vicasas** [comment]
I will close this, for some unknown reason after many days without working it worked again as expected. Thanks.
