### ISSUE TITLE
Enable in .tsx and .jsx files

### ISSUE THREAD

**Issue by mjbvz** [meganrogge/template-string-converter#8]
Issue Type: <b>Bug</b>

Enable this extension in TypeScript react (`.tsx`) and JavaScript react (`.jsx) files

These have language ids of `typescriptreact` and `javascriptreact`

Extension version: 0.1.0
VS Code version: Code - Insiders 1.50.0-insider (0c50e1db17168a738235bd7e5c02b9f05ea5df59, 2020-09-30T06:45:45.996Z)
OS version: Darwin x64 19.6.0

**Comment by mjbvz** [comment]
The extension already does work in these files but it looks like it is not activated by them. The [activation events](https://github.com/meganrogge/template-string-converter/blob/13eadfe079fc800b2b1575ecd56cbb634996ff80/package.json#L12) likely just need to be updated to include these language ids

**Comment by meganrogge** [comment]
fixed in version 0.1.1
