### ISSUE TITLE
Request: Similar extension to change regular `function` to `async function` when the `await` keyword is detected

### ISSUE THREAD

**Issue by hrastnik** [meganrogge/template-string-converter#89]
This is not actually an issue, but a request.

I love this extension, and I think a similar problem to solve would be to add the `async` keyword to a function when the `await` keyword is typed somewhere inside the functions body.

This is probably a lot to ask, but would you consider releasing such an extension?

**Comment by meganrogge** [comment]
Thanks for the request. I want to keep this extension simple, but you could make an extension that does specifically that 😄
